# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "colorize", "~> 0.8.1"
gem "tty-prompt", "~> 0.23.1"
gem "artii", "~> 2.1.2"
gem "tty-font", "~> 0.5.0" 
gem "pastel", "~> 0.8.0"
gem "rspec", "~> 3.11.0"